import Head from 'next/head'
import ClientOnly from '@/_component/ClientOnly'
import InitStyle from './InitStyle'
import StyledComponentsRegistry from '@/_utils/registry'

export const metadata = {
  title: 'Gaston Siow',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <body>
        <InitStyle/>
        <ClientOnly>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </ClientOnly>
      </body>
    </html>
  )
}
